name: advent
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  analyzer: ^8.1.1
  build: ^4.0.3
  build_runner: ^2.10.4
  code_builder: ^4.11.0
  dart_style: ^3.1.2
  lints: ^5.0.0
  source_gen: ^4.1.1
  test: ^1.24.0
